name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
      fail-fast: false

    runs-on: ${{matrix.runner}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Setup go.work
        run: |
          go work init . ./libdave ./golibdave

      - name: Install pkg-config (windows only)
        if: matrix.runner == 'windows-latest'
        run: |
          choco install pkgconfiglite

      - name: Install libdave
        run: |
          touch "$HOME/.bashrc"
          NON_INTERACTIVE=1 bash scripts/libdave_install.sh

      - name: Test build
        run: |
          source "$HOME/.bashrc"

          go build
          go build ./libdave
          go build ./golibdave
