name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  ci:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
      fail-fast: false

    runs-on: ${{matrix.runner}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Setup go.work
        run: |
          go work init . ./libdave ./golibdave

      - name: Install pkg-config (windows only)
        if: matrix.runner == 'windows-latest'
        run: |
          choco install pkgconfiglite

      - name: Install libdave
        run: |
          # Windows is missing a .bashrc by default
          touch "$HOME/.bashrc"
          bash scripts/libdave_install.sh

      # We unfortunately cannot just source the .bashrc because the `-latest` runners
      # contain a check at the top of the file to not run it if not in an interactive session
      - name: Test build
        run: |
          export PKG_CONFIG_PATH="$HOME/.local/lib/pkgconfig:$PKG_CONFIG_PATH"

          case "$(uname -s)" in
            Darwin) export DYLD_LIBRARY_PATH="$HOME/.local/lib:$DYLD_LIBRARY_PATH" ;;
            Linux) export LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH" ;;
            *) export PATH="$HOME/.local/lib:$PATH" ;;
          esac
          
          ls "$HOME/.local/lib/pkgconfig"

          go build
          go build ./libdave
          go build ./golibdave
