name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  libdave:
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, macos-15-intel, windows-latest]
      fail-fast: false

    runs-on: ${{matrix.runner}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Setup go.work
        run: |
          go work init . ./libdave ./golibdave

      - name: "[Windows Only] Add DLL to PATH"
        if: matrix.runner == 'windows-latest'
        run: |
          cp libdave/vendor/bin/win_x64/libdave.dll .

      - name: Test libdave
        run: |
          go test ./libdave
